name: PR Check Comment

on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Comment
        id: generate-comment
        run: |
          echo 'comment<<EOF' >> $GITHUB_OUTPUT
          echo '## PR Check Results' >> $GITHUB_OUTPUT

          if [[ -f ruff_ci_test/ecosystem_result.md ]]
          then
            echo "### Ecosystem" >> $GITHUB_OUTPUT
            cat ruff_ci_test/ecosystem_result.md >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
          fi

          if [[ -f ruff_ci_test/summary.md ]]
          then
            cat ruff_ci_test/summary.md >> $GITHUB_OUTPUT
          fi

          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create or update comment
        if: steps.generate-comment.outputs.comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          pr_number: ${{ steps.pr-number.outputs.pr-number }}
          message: ${{ steps.generate-comment.outputs.comment }}
          comment_tag: PR Check Results
