on:
  push:
    branches: master
  pull_request:
    branches: master


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: echo $GITHUB_RUN_ID
      - run: echo $GITHUB_EVENT_PATH
      - run: echo $GITHUB_SHA
      - run: echo $GITHUB_REF
      - run: python check_run_test.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
